site_name: MapYourGrid
site_url: 'https://MapYourGrid.org/'
site_description: We empower individuals, communities and nations around the world to map the electrical grid.
repo_name: 'MapYourGrid'
repo_url: 'https://github.com/open-energy-transition/MapYourGrid'

nav:
  - THE INITIATIVE : index.md
  - IMPACT: impact.md
  - STARTER-KIT: starter-kit.md
  - MAP ITüìç: map-it.md
  - TOOLS & STRATEGIES: tools.md
  - PROGRESS : progress.md
  - QUESTIONS? : questions.md
  - BLOG & TEAM : about-us-blog.md
  #    2025:
  #      - "Liberate the Grid": blog/firstrename.md

copyright: >
    <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
      Creative Commons Attribution 4.0 International License</a>
    | Map data from <a href="https://openstreetmap.org/copyright">OpenStreetMap</a>
    | <a href="https://MapYourGrid.org/privacy-policy/"> Read our Privacy Policy</a> 

theme:
  name: material
  custom_dir: overrides
  favicon: images/logos/MapYourGrid-logo.png
  logo: images/logos/MapYourGrid-logo.png
  palette:
    # Light Mode
    - scheme: default
      primary: custom
      accent: indigo
      toggle: false 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - search.suggest
    - navigation.top
    - navigation.sections
    - content.image.zoom
    

extra_css:
    - stylesheets/extra.css
    - stylesheets/landing.css
    - stylesheets/blog.css
    - https://cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.min.css


extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/open-energy-transition/MapYourGrid
  - icon: fontawesome/brands/discord
    link: https://discord.gg/a5znpdFWfD
  - icon: fontawesome/brands/youtube
    link: https://www.youtube.com/@MapYourGrid
  image: images/MapYourGrid.ico
  social_preview: images/website/mapyourgrid-preview.jpg

extra_javascript:
  - assets/javascripts/umami.js
  - assets/javascripts/gallery.js



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.md_in_html
  - admonition
  - pymdownx.details
  - attr_list


plugins:
  - search
  - glightbox:
        skip_classes:
            - thumb-gallery
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      skip_classes:
        - no-translate
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Espa√±ol  
          build: true
          site_name: "MapYourGrid"
          nav_translations:
            "THE INITIATIVE": "LA INICIATIVA"
            "IMPACT": "IMPACTO"  
            "STARTER-KIT": "KIT DE INICIO"
            "MAP ITüìç": "MAP ITüìç"
            "TOOLS & STRATEGIES": "HERRAMIENTAS Y ESTRATEGIAS"
            "PROGRESS": "PROGRESO"
            "QUESTIONS?": "¬øPREGUNTAS?"
            "BLOG & TEAM": "EQUIPO"
        - locale: fr
          name: Fran√ßais
          build: true
          nav_translations:
            "THE INITIATIVE": "L'INITIATIVE"
            "IMPACT": "IMPACT"  
            "STARTER-KIT": "KIT DE DEMARRAGE"
            "MAP ITüìç": "MAP ITüìç"
            "TOOLS & STRATEGIES": "OUTILS ET STRATEGIES"
            "PROGRESS": "PROGRES"
            "QUESTIONS?": "¬øQUESTIONS?"
            "BLOG & TEAM": "EQUIPE"
          site_name: "MapYourGrid"
      default_language: en
      material_alternate: true
  
  
