name: Update line length
on:
  workflow_dispatch: {} # enables manual trigger
  schedule:
    - cron: '0 3 * * 0' # runs every Sunday at 3 UTC (1 hour after tower count)
permissions:
  contents: write
jobs:
  fetch-line-length:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
  
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.17"
          enable-cache: true

      - name: üöÄ Run line length calculation script
        run: uv run python docs/py-scripts/line-length.py

      - name: ‚¨ÜÔ∏è Upload JSON to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-stats
          name: "Latest Automated Data"
          body: "Automated weekly update of data files. This release contains the latest generated stats."
          files: docs/data/line-length.json
          
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}