name: üìà Update Community Stats

on:
  workflow_dispatch: {} # Allows manual triggering
  schedule:
    - cron: '0 4 * * 1' # Runs every Monday (number 1) at 4 UTC

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name:  checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
  
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.17"
          enable-cache: true

      - name: üöÄ Run stats script for weekly update
        env:
          OSMCHA_TOKEN: ${{ secrets.OSMCHA_TOKEN }}
        run: uv run python docs/py-scripts/update_community_stats.py --mode weekly
       
      - name: ‚¨ÜÔ∏è Upload JSON to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-stats
          name: "Latest release of data"
          body: "Automated weekly update of json data files."
          files: docs/data/community-stats.json
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}